/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VtcRouteImport } from './routes/vtc'
import { Route as VerseAutoRouteImport } from './routes/verse-auto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as BilletterieRouteImport } from './routes/billetterie'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as IndexRouteImport } from './routes/index'

const VtcRoute = VtcRouteImport.update({
  id: '/vtc',
  path: '/vtc',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseAutoRoute = VerseAutoRouteImport.update({
  id: '/verse-auto',
  path: '/verse-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletterieRoute = BilletterieRouteImport.update({
  id: '/billetterie',
  path: '/billetterie',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/billetterie': typeof BilletterieRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/verse-auto': typeof VerseAutoRoute
  '/vtc': typeof VtcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/billetterie': typeof BilletterieRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/verse-auto': typeof VerseAutoRoute
  '/vtc': typeof VtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/billetterie': typeof BilletterieRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/verse-auto': typeof VerseAutoRoute
  '/vtc': typeof VtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance'
    | '/billetterie'
    | '/location'
    | '/login'
    | '/verse-auto'
    | '/vtc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance'
    | '/billetterie'
    | '/location'
    | '/login'
    | '/verse-auto'
    | '/vtc'
  id:
    | '__root__'
    | '/'
    | '/assurance'
    | '/billetterie'
    | '/location'
    | '/login'
    | '/verse-auto'
    | '/vtc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceRoute: typeof AssuranceRoute
  BilletterieRoute: typeof BilletterieRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  VerseAutoRoute: typeof VerseAutoRoute
  VtcRoute: typeof VtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vtc': {
      id: '/vtc'
      path: '/vtc'
      fullPath: '/vtc'
      preLoaderRoute: typeof VtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse-auto': {
      id: '/verse-auto'
      path: '/verse-auto'
      fullPath: '/verse-auto'
      preLoaderRoute: typeof VerseAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetterie': {
      id: '/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof BilletterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceRoute: AssuranceRoute,
  BilletterieRoute: BilletterieRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  VerseAutoRoute: VerseAutoRoute,
  VtcRoute: VtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
